name: 'Last successful commit'
description: 'Get the commit hash of the last successful workflow run on a given branch'
inputs:
  branch:
    description: 'Branch to get last successful commit from'
    required: true
    default: 'main'
  githubToken:
    description: 'Your GitHub access token'
    required: true
  workflowID:
    description: 'ID or filename of the workflow'
    required: true
  workflowEvent:
    description: 'Workflow event to get last successful commit from'
    required: true
    default: 'push'

outputs:
  commitHash:
    description: 'Last successful commit'

runs:
  using: 'node12'
  main: 'dist/index.js'
